## redis配置
server:
    redis:
        host: 127.0.0.1
        port: 6379
    database: 0
    jedis:
    pool:
        max‐active: 500
        max‐idle: 1000
        min‐idle: 4
spring:
    redis:
        host: 127.0.0.1
        port: 6379